# Generated by Django 6.0 on 2025-12-12 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sports_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Sports Category',
                'verbose_name_plural': 'Sports Categories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='turfs/')),
                ('description', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sports_category')),
            ],
            options={
                'verbose_name': 'Turf',
                'verbose_name_plural': 'Turfs',
                'ordering': ['-id'],
            },
        ),
    ]
